version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "Asia/Jerusalem"
    versioning-strategy: "increase"
    open-pull-requests-limit: 7
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
